version: '3.4'

services:
  mybooking.api:
    image: ${DOCKER_REGISTRY-}mybookingapi
    container_name: Booking.Api
    build:
      context: .
      dockerfile: MyBooking.API/Dockerfile
    depends_on:
      - mybooking-db

  mybooking-db:
    image: postgres:latest
    container_name: MyBooking.Db
    environment:
      - POSTGRES_DB=mybooking
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  mybooking-idp:
    image: jboss/keycloak:latest
    container_name: MyBooking.Identity
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/mybooking-realm-export.json
    volumes:
      - ./.containers/identity:/opt/jboss/keycloak/standalone/data
      - ./.files/mybooking-realm-export.json:/tmp/mybooking-realm-export.json
    ports:
      - 18080:8080
